import SideBar from "@/components/dashboard/sidBar/SideBar";
import styles from "./page.module.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className={styles.container}>
          <SideBar />
          <main className={styles.main}>{children}</main>
        </div>
      </body>
    </html>
  );
}
